// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"mall/app/cart/service/internal/biz"
	"mall/app/cart/service/internal/conf"
	"mall/app/cart/service/internal/data"
	"mall/app/cart/service/internal/server"
	"mall/app/cart/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	cartRepo := data.NewCartRepo(dataData, logger)
	cartUsecase := biz.NewCartUsecase(cartRepo, logger)
	cartService := service.NewCartService(cartUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, cartService, logger)
	grpcServer := server.NewGRPCServer(confServer, cartService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
